DROP TABLE IF EXISTS concerts CASCADE;
CREATE TABLE concerts (
  id          INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  band        VARCHAR(255),
  description VARCHAR(255),
  image_url   VARCHAR(255)
);

DROP TABLE IF EXISTS users CASCADE;
CREATE TABLE users (
  username VARCHAR(255) NOT NULL PRIMARY KEY,
  password VARCHAR(255)
);
